# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    environment:
      AWS_REGION: us-east-1

    working_directory: ~/prebid-universal-creative

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo apt install python-pip python-dev

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo npm install -g gulp

      - run: gulp build

      - aws-s3/copy:
          from: dist/creative.js
          to: 's3://assets.deployads.com/universal-creative/creative.js'
          arguments: '--acl public-read --cache-control "max-age=86400"'

workflows:
    build:
      jobs:
        - build:
            context: Sortable-Global
